(() => {
const $ = id => document.getElementById(id);
const STORAGE_KEY = "multiverse-v1";
const defaults = {
  wallpaper: "",
  title: "Entre dans le Multiverse.",
  games: [
    {id: cryptoId(),name:"Agar.io",url:"https://agar.io/",description:"Grandis, explore et évite les autres joueurs.",image:"",category:"IO"},
    {id: cryptoId(),name:"Slither.io",url:"https://slither.io/",description:"Fais grandir ton serpent dans l'arène.",image:"",category:"IO"},
    {id: cryptoId(),name:"2048",url:"https://play2048.co/",description:"Assemble les tuiles et vise le 2048.",image:"",category:"PUZZLE"}
  ],
  school: [
    {id:cryptoId(),name:"Pronote",url:"https://www.google.com/",description:"Notes, devoirs et vie scolaire.",icon:"▣"},
    {id:cryptoId(),name:"ENT",url:"https://www.google.com/",description:"Portail numérique de ton établissement.",icon:"⌂"},
    {id:cryptoId(),name:"Calendrier",url:"https://calendar.google.com/",description:"Organise tes dates et tes rappels.",icon:"▦"},
    {id:cryptoId(),name:"Wikipédia",url:"https://fr.wikipedia.org/",description:"Pour retrouver des informations utiles.",icon:"◎"}
  ]
};
function cryptoId(){return Math.random().toString(36).slice(2,10)}
function load(){try{const v=JSON.parse(localStorage.getItem(STORAGE_KEY));if(v&&Array.isArray(v.games)&&Array.isArray(v.school))return v}catch(e){}return structuredClone(defaults)}
let data=load(), currentGame=null, localWallpaper="";
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(data));}catch(e){alert("La sauvegarde a échoué. L'image est peut-être trop volumineuse : essaie une image plus légère ou une URL.");}}
function safeUrl(raw){try{const u=new URL(raw);return ["http:","https:"].includes(u.protocol)?u.href:null}catch{return null}}
function setWallpaper(){const url=localWallpaper||data.wallpaper;const bg=url?`url("${url.replace(/["\\]/g,"")}"), `:"";$("landing").style.backgroundImage=url?`linear-gradient(115deg,#080b12d9,#080b1266),url("${url.replace(/["\\]/g,"")}")`:"";$("wallpaperPreview").style.backgroundImage=url?`url("${url.replace(/["\\]/g,"")}")`:"";$("landingTitle").innerHTML=escapeHtml(data.title||"Entre dans le Multiverse.").replace(/\n/g,"<br>");}
function escapeHtml(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function switchScreen(){const landing=$("landing");const portal=$("portal");if($("player").classList.contains("hidden")===false){closePlayer();return}landing.classList.toggle("hidden");portal.classList.toggle("hidden");}
function openAdmin(tab="appearance"){$("admin").classList.remove("hidden");showTab(tab);renderAdmin();$("wallpaperUrl").value=data.wallpaper||"";$("welcomeTitle").value=data.title||"";setWallpaper()}
function closeAdmin(){$("admin").classList.add("hidden")}
function showTab(name){document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b.dataset.tab===name));["appearance","games","school"].forEach(t=>$("tab-"+t).classList.toggle("hidden",t!==name))}
function renderGames(){const q=$("gameSearch").value.trim().toLowerCase();const items=data.games.filter(g=>(g.name+" "+g.description+" "+g.category).toLowerCase().includes(q));$("gameCount").textContent=String(data.games.length).padStart(2,"0");$("gameGrid").innerHTML=items.map(g=>`<article class="game-card"><div class="game-art">${g.image&&safeUrl(g.image)?`<img src="${escapeHtml(safeUrl(g.image))}" alt="">`:`<span class="art-symbol">✦</span>`}<span class="game-tag">${escapeHtml(g.category||"PORTAL")}</span></div><div class="game-info"><h3>${escapeHtml(g.name)}</h3><p>${escapeHtml(g.description||"Un univers à découvrir.")}</p><div class="card-bottom"><span class="muted" style="font:10px 'DM Mono',monospace">WEB GAME</span><button class="play-btn" data-play="${escapeHtml(g.id)}">JOUER ↗</button></div></div></article>`).join("");$("emptyGames").classList.toggle("hidden",items.length>0);$("gameGrid").classList.toggle("hidden",items.length===0);document.querySelectorAll("[data-play]").forEach(b=>b.addEventListener("click",()=>playGame(b.dataset.play)))}
function renderSchool(){ $("schoolGrid").innerHTML=data.school.map(s=>`<a class="school-card" href="${escapeHtml(safeUrl(s.url)||"#")}" target="_blank" rel="noopener noreferrer"><span class="school-icon">${escapeHtml(s.icon||"↗")}</span><span><strong>${escapeHtml(s.name)}</strong><small>${escapeHtml(s.description||"Ouvrir l'application")}</small></span><span class="external">↗</span></a>`).join("")}
function renderAdmin(){renderAdminGames();renderAdminSchool()}
function renderAdminGames(){ $("adminGamesList").innerHTML=data.games.map((g,i)=>`<div class="admin-item" data-id="${g.id}"><div class="admin-item-top"><strong>EMPLACEMENT ${String(i+1).padStart(2,"0")}</strong><button class="remove" data-remove-game="${g.id}">Supprimer ×</button></div><div class="fields-two"><input data-field="name" value="${escapeHtml(g.name)}" placeholder="Nom du jeu"><input data-field="category" value="${escapeHtml(g.category||"")}" placeholder="Catégorie"></div><input data-field="url" value="${escapeHtml(g.url)}" placeholder="https://adresse-du-jeu"><input data-field="image" value="${escapeHtml(g.image||"")}" placeholder="URL de l'image (facultatif)"><textarea data-field="description" rows="2" placeholder="Description">${escapeHtml(g.description||"")}</textarea></div>`).join("")||`<p class="muted smalltext">Aucun jeu pour le moment. Clique sur « Nouveau ».</p>`;bindAdminFields("game")}
function renderAdminSchool(){ $("adminSchoolList").innerHTML=data.school.map((s,i)=>`<div class="admin-item" data-id="${s.id}"><div class="admin-item-top"><strong>APPLICATION ${String(i+1).padStart(2,"0")}</strong><button class="remove" data-remove-school="${s.id}">Supprimer ×</button></div><div class="fields-two"><input data-field="name" value="${escapeHtml(s.name)}" placeholder="Nom"><input data-field="icon" value="${escapeHtml(s.icon||"↗")}" placeholder="Icône (ex. ✦)"></div><input data-field="url" value="${escapeHtml(s.url)}" placeholder="https://adresse"><textarea data-field="description" rows="2" placeholder="Description">${escapeHtml(s.description||"")}</textarea></div>`).join("")||`<p class="muted smalltext">Aucune application configurée.</p>`;bindAdminFields("school")}
function bindAdminFields(type){const list=$(type==="game"?"adminGamesList":"adminSchoolList");list.querySelectorAll(".admin-item").forEach(el=>el.querySelectorAll("[data-field]").forEach(input=>input.addEventListener("change",()=>{const item=data[type==="game"?"games":"school"].find(x=>x.id===el.dataset.id);if(item){item[input.dataset.field]=input.value.trim();save();renderGames();renderSchool();}})));list.querySelectorAll("[data-remove-game]").forEach(b=>b.addEventListener("click",()=>{data.games=data.games.filter(x=>x.id!==b.dataset.removeGame);save();renderGames();renderAdminGames()}));list.querySelectorAll("[data-remove-school]").forEach(b=>b.addEventListener("click",()=>{data.school=data.school.filter(x=>x.id!==b.dataset.removeSchool);save();renderSchool();renderAdminSchool()}))}
function addGame(){const g={id:cryptoId(),name:"Nouveau jeu",url:"https://",description:"",image:"",category:"JEU"};data.games.push(g);save();renderGames();renderAdminGames();const el=$("adminGamesList").querySelector(`[data-id="${g.id}"]`);el?.scrollIntoView({behavior:"smooth",block:"center"});el?.querySelector('[data-field="name"]')?.select()}
function addSchool(){const s={id:cryptoId(),name:"Nouvelle application",url:"https://",description:"",icon:"↗"};data.school.push(s);save();renderSchool();renderAdminSchool()}
function playGame(id){const g=data.games.find(x=>x.id===id);if(!g)return;const url=safeUrl(g.url);if(!url){alert("Ajoute une URL valide commençant par https:// ou http:// dans l'administration.");return}currentGame=g;$("playerName").textContent=g.name;$("gameFrame").src=url;$("openExternal").onclick=()=>window.open(url,"_blank","noopener,noreferrer");$("player").classList.remove("hidden");$("frameNotice").classList.remove("hidden");setTimeout(()=>$("frameNotice").classList.add("hidden"),7000)}
function closePlayer(){$("player").classList.add("hidden");$("gameFrame").src="about:blank";currentGame=null}
function showView(view){const school=view==="school";$("gamesView").classList.toggle("hidden",school);$("schoolView").classList.toggle("hidden",!school);$("pageCrumb").textContent=school?"COLLÈGE":"GAME HUB";document.querySelectorAll(".nav").forEach(b=>b.classList.toggle("active",b.dataset.view===view))}
$("enterBtn").addEventListener("click",switchScreen);$("adminOpen").addEventListener("click",()=>openAdmin());$("topAdmin").addEventListener("click",()=>openAdmin());$("adminClose").addEventListener("click",closeAdmin);$("admin").addEventListener("click",e=>{if(e.target===$("admin"))closeAdmin()});document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>showTab(b.dataset.tab)));document.querySelectorAll(".nav").forEach(b=>b.addEventListener("click",()=>showView(b.dataset.view)));$("quickAdd").addEventListener("click",()=>{openAdmin("games");addGame()});$("emptyAdd").addEventListener("click",()=>{openAdmin("games");addGame()});$("schoolAdmin").addEventListener("click",()=>openAdmin("school"));$("addGame").addEventListener("click",addGame);$("addSchool").addEventListener("click",addSchool);$("gameSearch").addEventListener("input",renderGames);$("playerBack").addEventListener("click",closePlayer);$("playerClose").addEventListener("click",closePlayer);
$("saveAppearance").addEventListener("click",()=>{data.wallpaper=$("wallpaperUrl").value.trim();data.title=$("welcomeTitle").value.trim()||"Entre dans le Multiverse.";localWallpaper="";save();setWallpaper();closeAdmin()});
$("wallpaperUrl").addEventListener("input",()=>{localWallpaper="";$("wallpaperPreview").style.backgroundImage=safeUrl($("wallpaperUrl").value)?`url("${safeUrl($("wallpaperUrl").value)}")`:""});
$("wallpaperFile").addEventListener("change",e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>2_500_000){alert("Image trop lourde pour le stockage local (limite conseillée : 2,5 Mo).");e.target.value="";return}const reader=new FileReader();reader.onload=()=>{localWallpaper=reader.result;$("wallpaperUrl").value="";$("wallpaperPreview").style.backgroundImage=`url("${localWallpaper}")`;};reader.readAsDataURL(file)});
$("resetAll").addEventListener("click",()=>{if(confirm("Réinitialiser tous les réglages locaux ?")){localStorage.removeItem(STORAGE_KEY);data=structuredClone(defaults);localWallpaper="";save();setWallpaper();renderGames();renderSchool();renderAdmin();}});
document.addEventListener("keydown",e=>{if(e.key==="F8"){e.preventDefault();if(!$("admin").classList.contains("hidden"))closeAdmin();switchScreen()}if(e.key==="Escape"){if(!$("player").classList.contains("hidden"))closePlayer();else if(!$("admin").classList.contains("hidden"))closeAdmin()}});
setWallpaper();renderGames();renderSchool();
})();